=== Cesio-organizzazione-di/Progetto_XML-DOM/mappe.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT mappe(mappa *)>
<!ELEMENT mappa (nome, dimensione, descrizione, foto)>
<!ELEMENT nome(#PCDATA)>
<!ELEMENT descrizione(#PCDATA)>
<!ELEMENT foto(#PCDATA)>

=== Cesio-organizzazione-di/Progetto_XML-DOM/XML/mappe.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappe SYSTEM "mappe.dtd">
<mappe>
  <mappa>
    <nome>Canyon dei Re</nome>
    <dimensione>Piccola</dimensione>
    <descrizione>Un tempo semplice insediamento sul pianeta Solace, l'isola conosciuta come Canyon dei Re prosper&#242; grazie all'IMC, quando la scelse come luogo per ricerca e sviluppo. Era sede di una base aerea, di un impianto per il trattamento delle acque e di un'incredibile quantit&#224; di stabilimenti necessari per le operazioni dell'IMC, come ad esempio un progetto segretissimo sul funzionamento della tecnologia fasica e un programma volto alla creazione di un esercito di simulacri controllato da un'unica mente. All'apparenza, il Canyon dei Re non sembrava che una mera installazione dell'IMC che, se non altro, port&#242; stabilit&#224; e posti di lavoro sul pianeta.Per sfogarsi, i soldati di stanza partecipavano a combattimenti in stile gladiatorio in un'area che chiamavano "Arena". Molti anni pi&#249; tardi, quando la Commissione scelse il Canyon dei Re come sede di una nuova sanguinaria competizione, la zona di Arena rimase intatta, come per rendere omaggio ai combattimenti da cui derivarono gli Apex Games. L'isola &#232; cambiata molto da allora, la Torre del Repulsore &#232; stata abbattuta da un aggressore sconosciuto, un'esplosione in un deposito di simulacri abbandonato ha fatto sprofondare Skull Town e Arena, e la maggior parte dell'isola &#232; stata oggetto di scavi sotto l'occhio attento della Commissione. Nonostante i cambiamenti, sar&#232; sempre la mappa che per prima ha ospitato gli Apex Games.</descrizione>
    <foto>immagini/mappe/canyon.jpg</foto>
  </mappa>
  
  <mappa>
    <nome>Confini del mondo</nome>
    <dimensione>Media</dimensione>
    <descrizione>Talos &#232; un pianeta ostile tormentato da un'intensa attivit&#224; vulcanica. Per questo motivo un tempo era ritenuto inabitabile e solo un piccolo gruppo di oppositori alla tecnologia riusc&#236; a insediarsi. Ma quando un raro composto minerale fu scoperto in profondit&#224;, divent&#242; il centro dell'attivit&#224; dell'IMC. Furono costruite delle torri termoregolatrici per raffreddare i flussi di lava e permettere di estrarre le risorse. La struttura che le ospitava venne chiamata New Dawn ("Nuova Aurora"), e la citt&#224; di Confini del Mondo si svilupp&#242; tutt'intorno.Qualche decennio fa, un'esplosione in una delle torri congel&#242; fatalmente l'area circostante. La citt&#224; fu abbandonata e rimase solo una piccola comunit&#224; di cacciatori che un tempo disprezzavano la tecnologia moderna (ma l'accettarono provvisoriamente per seguire la loro eroina, Bloodhound). Tuttavia, le rovine e il terreno ricco di fonti di energia del pianeta attirarono l'attenzione di due gruppi importanti: la Commissione dei mercenari e la Hammond Robotics. Oggi, Confini del Mondo &#232; la seconda casa degli Apex Games nonch&#233; un centro operativo fondamentale della Hammond Robotics, che vi ha installato un impianto ultramoderno per iniziare l'estrazione delle risorse: il Planet Harvester. </descrizione>
    <foto>immagini/mappe/confini.jpg</foto>
  </mappa>
  
  <mappa>
    <nome>Olympus</nome>
    <dimensione>Grande</dimensione>
    <descrizione>Olimpo era una citt&#224; costruita su un sogno. Un'utopia fluttuante tra le nuvole che si estendono su Psamathe, dove un tempo le menti pi&#249; brillanti delle Terre Straniere si riunivano per scambiarsi idee e dare vita a incredibili scoperte scientifiche e artistiche. Ma non tutti i sogni hanno un lieto fine, e questo si trasform&#242; in un incubo: un incidente in un laboratorio di ricerca sperimentale gener&#242; una gigantesca bolla di energia fasica, costringendo gli abitanti ad abbandonare la citt&#224;.Tuttavia, Olimpo era alimentata da sistemi informatici all'avanguardia, perci&#242; non fu difficile trovare nuovi acquirenti tra l'&#233;lite delle Terre Straniere. Per 40 anni &#232; stata meta di vacanze lussuose, vantando diverse attrazioni turistiche. Purtroppo per&#242;, col passare del tempo la bolla di energia &#232; diventata instabile e sei mesi fa Olimpo &#232; stata interamente evacuata. Ora la Hammond Robotics, con l'aiuto della Commissione dei mercenari, ha trasformato la citt&#224; in una nuova arena per gli Apex Games, anche se il motivo resta un mistero. </descrizione>
    <foto>immagini/mappe/olimpo.jpg</foto>
  </mappa>
</mappe>
